language: cpp
compiler: clang
dist: trusty

env:
  - CXXFLAGS="-stdlib=libc++"

script:
  - ./autogen.sh
  - ./configure
  - make test

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libc++-dev
